export default {
    testEnvironment: "node",
    testMatch: ["<rootDir>/test/**/*.test.js"],
    collectCoverageFrom: [
        "src/models/Chat.js",
        "src/models/Wishlist.js",
        "src/models/Rating.js",
        "src/models/Comparison.js",
        "src/models/EmailJob.js",
        "src/middleware/verifyOwner.js",
        "src/middleware/verifyAdmin.js",
        "src/middleware/verifyPropertyOwner.js",
        "src/services/propertyDescriptionPromptService.js",
        "src/services/registrationPolicyService.js",
        "src/services/listingBillingService.js",
        "src/services/propertyLocationService.js",
        "src/services/propertySearchService.js",
        "src/services/emailTemplateService.js",
        "src/services/nidRegistryService.js",
        "src/services/nidVerificationService.js",
        "src/services/aiConversationService.js",
        "src/services/emailJobService.js",
        "src/services/emailNotificationService.js",
        "src/services/emailService.js",
        "src/services/sslcommerzService.js",
        "src/services/groqService.js",
        "src/services/webSearchService.js",
    ],
    coverageDirectory: "coverage",
};
